### ISSUE TITLE
Package installation issue

### ISSUE THREAD

**Issue by aswin-giridhar** [allenai/cartography#2]
Hi,
I am facing issue in installing the correct huggingface transformers version as the git branch in the requirements has been deleted. Could you please update the requirements.txt.
Regards,
Aswin

**Comment by prajjwal1** [comment]
It should work with `transformers==2.5.5`.

**Comment by aswin-giridhar** [comment]
@prajjwal1  thanks for the response, but the pypi repo for transformers does not have the version 2.5.5

**Comment by prajjwal1** [comment]
Try with `2.5` or somewhere around this.

**Comment by itaim** [comment]
I tried with `2.0.0`, `2.5`, `2.9.1`,`3.1.0` always getting `AttributeError: type object 'BertConfig' has no attribute 'pretrained_config_archive_map'` on `run_glue` import.

**Comment by Raghav1606** [comment]
Facing the same issue. Is there some quick fix for the same ?

**Comment by EricChang01** [comment]
@Raghav1606 it works for me with `transformers==2.6.0`, perhaps you can try some version around this.

**Comment by pskadasi** [comment]
lots of package installation issues
